/* 
 * File:   error_types.h
 * Author: alexl
 *
 * Created on 23 May 2025, 15:07
 */

#ifndef ERROR_TYPES_H
#define	ERROR_TYPES_H

typedef enum {
    LOCKOUT_REASON_NONE = 0xff,
    LOCKOUT_REASON_OVERVOLT = 0x01,
    LOCKOUT_REASON_UNDERVOLT = 0x02,
    LOCKOUT_REASON_OVERTEMP = 0x03,
    LOCKOUT_REASON_UNDERTEMP = 0x04,
    LOCKOUT_REASON_OVERCURRENT = 0x05,
    LOCKOUT_REASON_COMM_FAULT = 0x06,
    LOCKOUT_MEASURE_FAULT = 0x07,        
} lockout_reason_t;

typedef enum { 
    SHUTDOWN_REASON_NONE, 
    SHUTDOWN_REASON_TIMER,
    SHUTDOWN_REASON_CHARGE_DONE,
    SHUTDOWN_REASON_UNDER_V,
    SHUTDOWN_REASON_OVER_V,
    SHUTDOWN_REASON_UNDER_TEMP,
    SHUTDOWN_REASON_OVER_TEMP,
    SHUTDOWN_REASON_OVER_CURR,
    SHUTDOWN_REASON_WDT,
} shutdown_reason_t;

#endif	/* ERROR_TYPES_H */

